defaultSeverity: warning
extends:
    - stylelint-config-standard
    - stylelint-config-recommended-scss
    - stylelint-config-standard-scss
    - stylelint-config-sass-guidelines
plugins:
    - stylelint-scss
    - stylelint-order
rules:
  import-notation: 'string'
  # Disallows
  selector-max-id: 1
  # Nesting
  max-nesting-depth:
    - 4
    - ignore: ['blockless-at-rules', 'pseudo-classes']
  media-query-no-invalid: null
  # Selector names (override stylelint-config-sass-guidelines to allow `_`)
  selector-class-pattern:
    - ^[a-z0-9_\\-]+$
    - message: "Selector should be written in lowercase with hyphens (selector-class-pattern)"
  selector-no-qualifying-type:
    - true
    - ignore: ["class"]
  # Style Guide
  selector-max-compound-selectors: 6
  scss/dollar-variable-pattern: "[a-z][a-zA-Z_-]+"
  order/properties-alphabetical-order: true
