language: generic
dist: xenial
os: linux
git:
  depth: 1
addons:
  apt:
    packages:
    - bsdtar
    - curl
    - nodejs
script:
  - sh -x ./build.sh
env:
  - THEME_VERSION=${TRAVIS_TAG:-$TRAVIS_BRANCH-$TRAVIS_COMMIT}
deploy:
  token: $DEPLOY_OAUTH_TOKEN
  file: "target/clarin_bootstrap-${THEME_VERSION}.tar.gz"
  on:
    all_branches: true
    tags: true
  overwrite: true
  provider: releases
  skip_cleanup: true
notifications:
  email:
    on_success: change
    on_failure: always
