name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2  
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/*/}
      - name: Build theme
        run: |
          sudo apt-get install bsdtar curl nodejs
          sh -x ./build.sh
        env:
          THEME_VERSION: ${{ steps.get_version.outputs.VERSION }}
      - name: Upload build package
        uses: actions/upload-artifact@v2
        with:
          name: build-package
          path: dist/clarin_bootstrap-${{ steps.get_version.outputs.VERSION }}.tar.gz
  release:
    # Also run when a tag is pushed to the repository
    if: github.event_name == 'release' || github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: ubuntu-18.04
    steps:
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/*/}
    - name: Download build package from build job
      uses: actions/download-artifact@v2
      with:
        name: build-package
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: clarin_bootstrap-${{ steps.get_version.outputs.VERSION }}.tar.gz
        asset_name: clarin_bootstrap-${{ steps.get_version.outputs.VERSION }}.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
