name: CI

on:
  push:
  pull_request:
  release:
    types: [published]
  workflow_dispatch:
  schedule:
  - cron: "23 2 12 * *"
jobs:
  prepare:
    runs-on: ubuntu-18.04
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
      create_release: ${{ steps.check_release.outputs.CREATE_RELEASE }}
    steps:
      - name: Get build version
        id: get_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF##*/}
          echo "Version: ${GITHUB_REF##*/}"
        # Releases created via the GitHub webGUI will also create and push a tag.
        # Both events will trigger this workflow, so we cancel the run for tags and allow it for releases.
      - name: Check if workflow is running for a tagged release
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        id: check_release
        run: |
          URL="https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ steps.get_version.outputs.VERSION }}"
          StatusCode=$(curl -o -I -L -s -w "%{http_code}" -X GET -G $URL)
          if [ "$StatusCode" == 200 ]; then
            echo "GitHub release already exists: stopping this workflow.\nSee parallel `Release` workflow."
            echo ::set-output name=CREATE_RELEASE::false
          else
            echo "Tag pushed without release: building and creating a new GitHub release."
            echo ::set-output name=CREATE_RELEASE::true
          fi
  provision-environment:
    needs: [prepare]
    # Run workflow proper for: github releases, tag pushes without github release and regular pushes (not tag)
    if: github.event_name == 'release' || needs.prepare.outputs.create_release == 'true' || !contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: '50'
      - name: Install npm dependencies
        id: npm_install
        run: |
          echo 'Installing npm dependencies ...'
          rm -fr node-modules
          npm ci
      - name: 'Tar workspace'
        run: tar -cvf workspace.tar .
      - uses: actions/upload-artifact@v2
        with:
          name: workspace
          path: workspace.tar
          retention-days: 1
  lintJS:
    needs: [provision-environment]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: workspace
      - name: 'Untar workspace'
        run: tar -xf workspace.tar .
      - name: Lint Javascript
        id: lint_js
        run: gulp lintscripts
  lintSCSS:
    needs: [provision-environment]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: workspace
          path: .
      - name: 'Untar workspace'
        run: tar -xf workspace.tar .
      - name: Lint SCSS
        id: lint_js
        run: gulp lintstyles
  build:
    needs: [prepare, lintJS, lintSCSS]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: workspace
      - name: 'Untar workspace'
        run: tar -xf workspace.tar .
      - name: Build
        run: sh -x ./build.sh ci
        env:
          THEME_VERSION: ${{ needs.prepare.outputs.version }}
      - name: Upload build package
        uses: actions/upload-artifact@v2
        with:
          name: drupal-theme-build-package
          path: dist/clarin_bootstrap-${{ needs.prepare.outputs.version }}.tar.gz

  publish:
    needs: [prepare, build]
    runs-on: ubuntu-18.04
    steps:
      - name: Get build package from build job
        uses: actions/download-artifact@v2
        with:
          name: drupal-theme-build-package
      - name: 'Untar build package'
        run: ls -Fla && tar -xf clarin_bootstrap-${{ needs.prepare.outputs.version }}.tar.gz
      - name: Publish to distribution repository
        uses: s0/git-publish-subdir-action@v2.5.0
        env:
          REPO: git@github.com:clarin-eric/clarin-drupal-bootstrap-theme-dist.git
          BRANCH: ${{ needs.prepare.outputs.version }}.x
          FOLDER: clarin_bootstrap
          SSH_PRIVATE_KEY: ${{ secrets.SSH_DEPLOY_DIST_KEY }}
          MESSAGE: "Updated from https://github.com/clarin-eric/clarin-drupal-bootstrap-theme/commit/{sha}\nLast commit message:\n{msg}"
  